/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-primary-fixed": "#001b3c",
          "on-primary-container": "#c0d6ff",
          "tertiary-fixed": "#d5e3ff",
          "surface-container-low": "#f3f4f5",
          "secondary-container": "#77b4fd",
          "surface-container-high": "#e7e8e9",
          "background": "#f8f9fa",
          "on-background": "#191c1d",
          "surface-container-lowest": "#ffffff",
          "primary-container": "#0b5cad",
          "primary-fixed": "#d5e3ff",
          "on-tertiary-fixed-variant": "#1f477b",
          "surface-container-highest": "#e1e3e4",
          "on-error-container": "#93000a",
          "secondary-fixed": "#d2e4ff",
          "error-container": "#ffdad6",
          "tertiary": "#1d4579",
          "outline": "#727783",
          "on-primary-fixed-variant": "#004689",
          "on-error": "#ffffff",
          "secondary": "#0f61a4",
          "inverse-surface": "#2e3132",
          "primary": "#004485",
          "error": "#ba1a1a",
          "on-secondary-fixed-variant": "#004880",
          "secondary-fixed-dim": "#a1c9ff",
          "on-secondary-container": "#00457a",
          "surface-bright": "#f8f9fa",
          "surface-tint": "#115eaf",
          "on-tertiary": "#ffffff",
          "inverse-on-surface": "#f0f1f2",
          "on-surface-variant": "#424751",
          "on-tertiary-container": "#c0d6ff",
          "on-primary": "#ffffff",
          "on-secondary": "#ffffff",
          "on-secondary-fixed": "#001c37",
          "surface-dim": "#d9dadb",
          "surface": "#f8f9fa",
          "surface-container": "#edeeef",
          "tertiary-container": "#385d92",
          "tertiary-fixed-dim": "#a7c8ff",
          "on-surface": "#191c1d",
          "outline-variant": "#c2c6d3",
          "inverse-primary": "#a8c8ff",
          "on-tertiary-fixed": "#001b3c",
          "surface-variant": "#e1e3e4",
          "primary-fixed-dim": "#a8c8ff"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "section-padding": "48px",
          "stack-md": "16px",
          "container-max": "1280px",
          "gutter": "24px",
          "stack-sm": "8px",
          "stack-lg": "32px",
          "margin-mobile": "16px"
      },
      "fontFamily": {
          "body-lg": ["Inter", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "document-text": ["Times New Roman", "serif"],
          "h1": ["Poppins", "sans-serif"],
          "label-caps": ["Inter", "sans-serif"],
          "body-sm": ["Inter", "sans-serif"],
          "h3": ["Poppins", "sans-serif"],
          "h2": ["Poppins", "sans-serif"]
      },
      "fontSize": {
          "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "body-md": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "document-text": ["16px", {"lineHeight": "1.8", "fontWeight": "400"}],
          "h1": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "label-caps": ["11px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
          "body-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "400"}],
          "h3": ["20px", {"lineHeight": "1.4", "fontWeight": "500"}],
          "h2": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}